export const data={
    firstName: '',
    middleName:'',
    lastName:'',
    contactNo:'',
    Dob:'',
    address:'',
    hospitalName:'',
    gender:'',
    countryName:'',
    stateName:'',
    cityName:'',
    pincode:'',
    martialStatus:'',
}
