export const data={
    title:'',
    firstName: '',
    middleName:'',
    lastName:'',
    contactNo:'',
    dob:'',
    address:'',
    hospitalName:'',
    gender:'',
    countryName:'',
    stateName:'',
    cityName:'',
    pincode:'',
    martialStatus:'',
}
